# Generated by Django 6.0 on 2026-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
