# Generated by Django 6.0 on 2026-07-18 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['verification_status', 'is_verified'], name='judges_judg_verific_ed50f0_idx'),
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['judge_display_name'], name='judges_judg_judge_d_2c1860_idx'),
        ),
    ]
