# Generated by Django 6.0 on 2026-07-18 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('funded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FUNDING_REQUIRED', 'Funding Required'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('DISPUTED', 'Disputed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=30)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('dispute_deadline', models.DateTimeField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('chain_reference', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.company')),
            ],
        ),
    ]
