# Generated by Django 6.0 on 2026-07-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='judges.judge'),
        ),
    ]
