# Generated by Django 6.0 on 2026-07-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'status'], name='contracts_c_company_a233d3_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['student', 'status'], name='contracts_c_student_c0ed5a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at', 'status'], name='contracts_c_created_5dc7c9_idx'),
        ),
    ]
