# Generated by Django 6.0.6 on 2026-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('ACTIVE', 'Active'), ('FUNDING_REQUIRED', 'Funding Required'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('DISPUTED', 'Disputed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
