# Generated by Django 6.0 on 2026-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='funded_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='contract',
            name='released_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
