# Generated by Django 6.1 on 2026-08-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_funded_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
