# Generated by Django 6.0 on 2026-07-18 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('UNFAIR_EVALUATION', 'Unfair Evaluation'), ('SCOPE_MISMATCH', 'Scope Mismatch'), ('INCOMPLETE_WORK', 'Incomplete Work'), ('COMMUNICATION_BREAKDOWN', 'Communication Breakdown'), ('PAYMENT_ISSUE', 'Payment Issue'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('PARTIALLY_RESOLVED', 'Partially Resolved'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('decision', models.CharField(blank=True, choices=[('RELEASE_PAYMENT', 'Release Payment'), ('REFUND_COMPANY', 'Refund Company'), ('PARTIAL_PAYMENT', 'Partial Payment')], default='', max_length=50)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('split_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('dispute_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('judge_reward', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
