# Generated by Django 6.0 on 2026-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='judge_reward',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolution_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
