# Generated by Django 6.0 on 2026-07-18 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('course_name', models.CharField(blank=True, default='', max_length=255)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, default='')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
