# Generated by Django 6.0 on 2026-07-18 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SUBMISSION_RECEIVED', 'Submission Received'), ('AI_REPORT_READY', 'AI Report Ready'), ('DISPUTE_CREATED', 'Dispute Created'), ('JUDGE_ASSIGNED', 'Judge Assigned'), ('DECISION_COMPLETED', 'Decision Completed'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('CONTRACT_UPDATE', 'Contract Update'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=50)),
                ('channel', models.CharField(choices=[('IN_APP', 'In App'), ('EMAIL', 'Email'), ('BOTH', 'Both')], default='IN_APP', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('target_url', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_status', models.CharField(db_index=True, default='PENDING', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
