/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IInternPayEscrow {
    function isAlive() external view returns (bool);

    function initialize() external;

    function createEscrow(address intern, address judge, uint256 total_amount) external returns (uint64);

    function addMilestone(uint64 escrow_id, uint32 milestone_id, uint256 amount, uint64 deadline) external;

    function lockFunds(uint64 escrow_id) external payable;

    function submitMilestone(uint64 escrow_id, uint32 milestone_id, bytes32 evidence_hash) external;

    function approveMilestone(uint64 escrow_id, uint32 milestone_id) external;

    function rejectMilestone(uint64 escrow_id, uint32 milestone_id) external;

    function cancelEscrow(uint64 escrow_id) external;

    function raiseDispute(uint64 escrow_id, uint32 milestone_id, bytes32 evidence_hash) external;

    function depositDisputeBond(uint64 escrow_id, uint32 milestone_id) external payable;

    function resolveDispute(uint64 escrow_id, uint32 milestone_id, uint8 decision, uint256 released_to_intern, uint256 refunded_to_company) external;
}
