# Generated by Django 6.0 on 2026-07-18 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['verification_status', 'is_verified'], name='students_st_verific_da9450_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution_name'], name='students_st_institu_0a4db3_idx'),
        ),
    ]
