# Generated by Django 6.0 on 2026-07-18 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_resolved_disputes', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
