# Generated by Django 6.0 on 2026-07-18 13:24

import django.db.models.deletion
import internpay.utils.files
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('milestones', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_url', models.URLField(blank=True, default='')),
                ('demo_url', models.URLField(blank=True, default='')),
                ('figma_url', models.URLField(blank=True, default='')),
                ('documentation_url', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('EVALUATING', 'Evaluating'), ('APPROVED', 'Approved'), ('APPROVED_WITH_NOTES', 'Approved With Notes'), ('HUMAN_REVIEW', 'Human Review'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed'), ('RESOLVED', 'Resolved')], db_index=True, default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evaluated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contracts.contract')),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='milestones.milestone')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_score', models.PositiveIntegerField(default=0)),
                ('design_score', models.PositiveIntegerField(default=0)),
                ('requirement_score', models.PositiveIntegerField(default=0)),
                ('functionality_score', models.PositiveIntegerField(default=0)),
                ('overall_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendation', models.CharField(choices=[('APPROVED', 'Approved'), ('APPROVED_WITH_NOTES', 'Approved With Notes'), ('HUMAN_REVIEW', 'Human Review'), ('REJECTED', 'Rejected')], db_index=True, default='HUMAN_REVIEW', max_length=30)),
                ('explanation', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('model_version', models.CharField(blank=True, default='', max_length=120)),
                ('evaluated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=internpay.utils.files.submission_upload_path)),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contract', 'status'], name='submissions_contrac_daa79c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='submissions_student_c504ac_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at', 'status'], name='submissions_submitt_13f855_idx'),
        ),
        migrations.AddIndex(
            model_name='aireport',
            index=models.Index(fields=['overall_score', 'recommendation'], name='submissions_overall_780df8_idx'),
        ),
        migrations.AddIndex(
            model_name='aireport',
            index=models.Index(fields=['status', 'evaluated_at'], name='submissions_status_fe405d_idx'),
        ),
    ]
