# Generated by Django 6.0.6 on 2026-07-21 15:17

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=42, validators=[apps.common.validators.validate_wallet_address]),
        ),
    ]
